# Generated by Django 6.0.1 on 2026-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
