# Generated by Django 6.0.1 on 2026-01-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_footballclub_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
    ]
